version: 0.9.{build}

pull_requests:

  do_not_increment_build_number: true

branches:

  only:

  - master

skip_tags: true

configuration:

- Debug

- Release

platform: Any CPU

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

cache: packages -> **\packages.config

before_build:

- cmd: >-

    git submodule update --init --recursive



    nuget restore

build:

  verbosity: minimal

after_build:

- cmd: >-

    7z a -tzip KDSharp_KDTree_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\Binaries\KDVisuals\%CONFIGURATION%\*

artifacts:

- path: '*.zip'

  name: Release

deploy:

- provider: GitHub

  auth_token:

    secure: 0D/RfRV/f6GheHsPAdrIJRQT4C3EGC064X1xbq4DSzQWK5s9J/7Et4HV/51ozVe3

  artifact: Release
  
